### ISSUE TITLE
Protocols - idea

### ISSUE THREAD

**Issue by Piorin** [reinder42/SwiftCheatsheet#7]
Hello Reinder!

I've prepared a basics for protocol subsection but I'm not sure it's enough. I'm trying to keep it brief but I don't want to miss on crucial information. Could you check the idea and tell me if it's enough or should I add something else?

**Protocols**

Protocols define a "contract" - they define a set of methods and properties that a type must implement if it _conforms_ to the protocol.

Protocols are declared like this:

```
protocol Jedi {
        var name: String { get set }
        var rank: String { get set }
        func useTheForce()
    }
```

Example of struct that conform to the `Jedi` protocol:

```
    protocol Jedi {
        var name: String { get set }
        var rank: String { get set }
        func useTheForce()
    }

    struct Master: Jedi {
        var name = "Obi-Wan Kenobi"
        var rank = "Jedi Master"
        
        func useTheForce() {
            print("These aren't the droids you're looking for.")
        }
    }
```

**Comment by reinder42** [comment]
Great work! Thanks :-) I have a few comments:

- I see what you did with `Jedi` being the protocol for `Master`, but I think the example you used is more appropriate for subclass-superclass. I think it's smarter if you use the protocol to decorate a base class with a certain capability (and also not pre-fill the `name` and `rank` properties)
- What about a `Stormtrooper` base struct with `name` and `rank`, and a protocol that's called `Healing` or `Healer` with a `heal()` function. This implies that a `Stormtrooper`, `Swamptrooper`, `TiePilot` etc. are good on their own, but they can also heal others _if_ they adopt and conform to the `Healing` protocol. This is closer related to, say, custom Swift objects and `Comparable`.

I hope that makes sense :-)

**Comment by Piorin** [comment]
Hmm... I hope I understood your comment correctly(I will just paste the code - without the definition) - the values of properties `name` and `rank` are not prefiled(properties in protocol - must have { get } or { get set } or they throw error).  

```
protocol Healer {
    var name: String { get set }
    var rank: String { get set }
    func heal()
}

struct TiePilot {
    var name: String = ""
    var rank: String = ""
    func combat() {
        print("Combat mode: Activated!")
    }
}

struct Stormtrooper: Healer {
    var name: String = ""
    var rank: String = ""
    func heal() {
        print("Healing mode: Activated!")
    }
}
```
I've included `TiePilot` struct for sake of comparison - `TiePilot` or any other Imperial unit like `Swamptrooper` can fight just fine but it can also adopt `Healer` protocol and provide additional support on the battlefield. If you want I can remove it in the final version :)

**Comment by reinder42** [comment]
Great! I think `name` and `rank` can me moved out of `Healer` and into `TiePilot` and/or `Stormtrooper`. Maybe a trooper has a name and rank, and a pilot a rank and preferred spaceship or something? That way we can really see how `Healer` can be used to compose the `healing()` capability.

Feel free to PR :-) Thanks again!

**Comment by Piorin** [comment]
Created PR - Protocols update - closing Issue now. In case of any issue with PR please let me know and I will fix it :)
